[package]
name = "zkp"
version = "0.3.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
license = "CC0-1.0"
repository = "https://github.com/hdevalence/zkp"
documentation = "https://docs.rs/zkp"
categories = ["cryptography"]
keywords = ["cryptography", "curve25519", "zero-knowledge", "NIZK", "compiler"]
description = "This crate has an experimental zero-knowledge proof compiler implemented using Rust macros"
exclude = [
    ".gitignore"
]

[dependencies]
sha2 = "^0.6"
rand = "^0.3"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
bincode = "0.9.2"

[dependencies.curve25519-dalek]
features = ["serde", "nightly"]
version = "^0.12"

[replace]
"curve25519-dalek:0.12.1" = { git = "https://github.com/hdevalence/curve25519-dalek", branch="feature/ristretto_r2" }

