[package]
name = "zkp"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]

[dependencies]
sha2 = "^0.4"
rand = "^0.3"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
serde_cbor = "0.6"

[dependencies.curve25519-dalek]
features = ["yolocrypto", "serde", "nightly"]
version = "^0.9"

